# http://localhost:3000/usuario


# ###
# POST http://localhost:3000/usuario HTTP/1.1
# content-type: application/json

# {
#    "id": 4,
#     "username": "lsouza",
#     "email": "leo@email.com",
#     "senha": "123456"
# }

# ###

# http://localhost:3000/clientes